version: '3'

services: 
  app:
    image: XXXXX/YYYYY:0.0.1
    build: ./app
    ports:
      - "3000:3000"     
    restart: always
    links: 
      - mongo
    # PROD - VOLUMES
    volumes:
      - ernestvolume:/usr/src/app
  mongo:
    image: mongo
    ports: 
      - "27017:27017"

volumes:
  ernestvolume:

## Can go to playwithdocker to test it out
## Need to create your volume first though  
